### ISSUE TITLE
[Bug : Tour Info Tooltip] Wrong elevation values 

### ISSUE THREAD

**Issue by FJBDev** [mytourbook/mytourbook#1265]
### What happened ?

When I look at a recent tour, the total elevation gain/loss is correct but the ascent is totally wrong
See the picture below where 1400 & -1404ft are correct but 4,325 & 4307 are not.

![image](https://github.com/mytourbook/mytourbook/assets/25235665/19b05571-e000-4d2b-ac4a-43c12e0a9002)

### Version

24.1

### System

All

**Comment by wolfgang-ch** [comment]
There are 2 issues

* Imperial value is wrong by dividing it 2 times from metric, fixed in https://github.com/mytourbook/mytourbook/commit/304481a60241ee5609ce5dd2cf874e809319a32a
* The other issue is, sometimes the value is wrong by factor ~4 and also for the metric system

![image](https://github.com/mytourbook/mytourbook/assets/1283445/98b0e7d0-6621-467d-a7d1-4dfd3f3e9029)

**Comment by FJBDev** [comment]
I can still see the issue in the official 24.1 release. 
I will investigate with my production database

**Comment by FJBDev** [comment]
>also for the metric system but I cannot reproduce it when it happens

After investigation, here is how to reproduce it:
- Import a tour
- Display the tour tooltip from the tour chart
- Change the measurement system (metric to imperial)
- Display the tour tooltip from the tourchart
=> the Ascent/Descent will be **ok** :heavy_check_mark: 
- Open the Tour Segmenter view and change the DP
- Display the tour tooltip from the tourchart
=> the Ascent/Descent will be **wrong** :x: 

This is my guess to why it happens:
When changing the measurement system, [this](https://github.com/mytourbook/mytourbook/blob/ba4bf17dd08402b89f2ad5bc108cbb94a24631a2/bundles/net.tourbook/src/net/tourbook/tour/TourInfoUI.java#L2396) does not get recomputed because [this function](https://github.com/mytourbook/mytourbook/blob/ba4bf17dd08402b89f2ad5bc108cbb94a24631a2/bundles/net.tourbook/src/net/tourbook/data/TourData.java#L6076) only recomputed when the DP tolerance or flat gradient preferences have changed.
It's fine because the value is already computed and is converted properly [here](https://github.com/mytourbook/mytourbook/blob/ba4bf17dd08402b89f2ad5bc108cbb94a24631a2/bundles/net.tourbook/src/net/tourbook/tour/TourInfoUI.java#L2450).
However, when the subsequent change of the DP preference is made, it will trigger the recomputation of the values but because this [serie](https://github.com/mytourbook/mytourbook/blob/ba4bf17dd08402b89f2ad5bc108cbb94a24631a2/bundles/net.tourbook/src/net/tourbook/data/TourData.java#L6092) is not in metric but in the current measurement system, then it will be wrong when it is again divided one more time [here](https://github.com/mytourbook/mytourbook/blob/ba4bf17dd08402b89f2ad5bc108cbb94a24631a2/bundles/net.tourbook/src/net/tourbook/tour/TourInfoUI.java#L2450)

**Comment by FJBDev** [comment]
> It looks like that this fix [ea20f7d](https://github.com/mytourbook/mytourbook/commit/ea20f7d51ee281a48da1d1e7d70c443f60b0c9fb) solved this issue

I confirm that the issue is resolved 👍
