### ISSUE TITLE
[Bug : Tourbook Selected Tours]  Selected tours are changing after some actions

### ISSUE THREAD

**Issue by mff73** [mytourbook/mytourbook#954]
### What happened ?

Here are two examples, but i am pretty sure to have other situations, but can't remember now.

Process#1 : select some tours, change some tags and after action is completed the selected tours are not the same as initially
Result : if one need to do other actions on the same list of tours, selection needs to be done again, and if not, action is done on wrong list of tours.

Example : 3 selected tours (23/10 + 20/10 + 13/10)
![image](https://user-images.githubusercontent.com/50132146/198214987-739a99a5-ea27-4344-b60a-4a71107df800.png)

want to change one tag by another --> delete first the wrong tag (Geonaute2-Pile8)
![image](https://user-images.githubusercontent.com/50132146/198215191-a5ab3903-ae19-4e81-b12f-e181b57f50ce.png)

and boum, selected tour are changed (20/10 + 16/10 + 9/10)
![image](https://user-images.githubusercontent.com/50132146/198215287-d959245a-f342-4b16-be2c-b2e1324a7be6.png)

Process#2 : select one tour (not the first top one), click on Tour Book option and tick and untick the display sum (sorry my MTB is in french), and each tick/untick will select another tour
Tour selected 23/10
![image](https://user-images.githubusercontent.com/50132146/198217052-0d229c4a-b286-4c79-8444-c38175d21015.png)
Tick the box
![image](https://user-images.githubusercontent.com/50132146/198217141-6c77d104-eba8-4979-a4b9-a93adabfc44e.png)
Tour 20/10 is now selected
![image](https://user-images.githubusercontent.com/50132146/198217216-882aae35-17cc-4a86-a524-50771f41d706.png)
untick the box, and 16/10 is selected
![image](https://user-images.githubusercontent.com/50132146/198217273-1235f365-34c1-4d8e-b43f-3b1d1674707c.png)
and it is not just the next one, sometimes it jumps of multiples tours. After just few ticks, i am now selected with 11/08 :)
![image](https://user-images.githubusercontent.com/50132146/198217541-a4fba14a-a397-4579-a4a9-4723027f6116.png)

### Version

22.8.0

### System

Windows

**Comment by wolfgang-ch** [comment]
Currently the total row is only displayed when TourBook view is categorized. So I fixed this part of the bug in https://github.com/mytourbook/mytourbook/commit/3e7c295b316f8f764773adaeb6fa6be11774512c by disabling the checkbox when the flat TourBook view is displayed

**Comment by wolfgang-ch** [comment]
This is now partly fixed, see comment in this commit https://github.com/mytourbook/mytourbook/commit/3bf7bffc7b6fd6764d9f834e998cb571bbb3d115

**Comment by mff73** [comment]
Hi Wolfgang.
thanks for both fixes. I am just not understanding from your comment "partly" fixed, what is still not fixed ?

**Comment by wolfgang-ch** [comment]
After tours are modified, e.g. tag(s) added or removed, then the tour list is reloaded and reselected. But the reselected tours, are looking reselected however when you then open the context menu again on the "selected" tours, during the opening, the "selected" tours get's deselected and just the tour under the mouse is selected. This behavior do not occure when you newly select tours and open the context menu (as many times as you want) without doing any action. Just the reloading of the flat tour list seems to have a reselection problem.

I debugged this issue for several hours and gave up for now. You need to dive deep into this complex selection and menu code and this can take several days until you maybe find the problem, or not.

**Comment by mff73** [comment]
Argh, i am able to simulate this also. Thanks for explanation, and good luck to find the issue one day 🤞 i am sorry not to be a developper and couldn't help 😥
It not high priority bug, just user need to be careful of which tours are "reselected" before any new mass action.
Thanks.

**Comment by wolfgang-ch** [comment]
I could fix the bug that the wrong tours are re-selected but they are only optically selected and not fully selected in the backend, there is something which I missed
